Add setup docs for linux
skycoin/wiki pull request #17
Opened 2021-10-05 14:19 UTC by libronlopes

add skywire setup instructions for linux

2021-10-05 14:38 UTC, jdknives requested changes

2021-10-05 14:38 UTC, jdknives commented on docs/software/skywire/setup/linux.md
> +Skywire requires a Golang version of 1.13 or higher.
We require a version of 1.16 or higher.

2021-10-05 14:38 UTC, jdknives commented on docs/software/skywire/setup/linux.md
> +Skywire can be statically built. For instructions check [the docs.](https://github.com/skycoin/skywire/blob/develop/docs/static-builds.md)
This should be taken out as it references back to the repo. Instead, make a separate page called `Static builds` in the `Setup` section.

2021-10-05 14:38 UTC, jdknives commented on docs/software/skywire/setup/linux.md
> +$ make build; make install
We are missing the comment where it installs the binaries to and that it requires PATH to include GOBIN

2021-10-05 14:38 UTC, jdknives commented on docs/software/skywire/setup/linux.md
> +# **Configure Skywire**
The whole part below here should be shortened to a very brief explanation of 

1. User can generate default config with `skywire-cli visor gen-config` 
2. Then run with `skywire-visor -c skywire-config`

For more details they should check out the Configuration section.

2021-10-05 14:38 UTC, jdknives commented on docs/software/skywire/setup/linux.md
> +Skywire requires a Golang version of 1.13 or higher.
Below this we should have a menu like this for explaining/linking how to install Golang, git and make on the following distributions

- Debian
- Arch

2021-10-05 14:38 UTC, jdknives commented on docs/software/skywire/setup/linux.md
> +Skywire requires a Golang version of 1.13 or higher.
![image](https://user-images.githubusercontent.com/36450093/136044803-93849692-b0cf-4865-85bd-86ae482efdf9.png)

2021-10-05 14:40 UTC, libronlopes commented on docs/software/skywire/setup/linux.md
> +Skywire requires a Golang version of 1.13 or higher.
Okay

2021-10-05 14:40 UTC, libronlopes commented on docs/software/skywire/setup/linux.md
> +Skywire can be statically built. For instructions check [the docs.](https://github.com/skycoin/skywire/blob/develop/docs/static-builds.md)
Okay

2021-10-05 14:42 UTC, libronlopes commented on docs/software/skywire/setup/linux.md
> +$ make build; make install
Okay. Will add it.

2021-10-05 14:43 UTC, libronlopes commented on docs/software/skywire/setup/linux.md
> +# **Configure Skywire**
Okay

2021-10-08 15:18 UTC, jdknives commented on docs/software/skywire/setup/macos.md
> +make install will install binaries to `GOBIN`. Hence it requires path to be set correctly.
`path` here is unclear. We are talking about the `$PATH` or `PATH` variable which is an environment variable. We also may need to point out that they should follow the Go installation instructions here. Not sure if Brew sets the PATH up correctly itself https://golang.org/doc/install

2021-10-08 15:19 UTC, jdknives commented on docs/software/skywire/setup/macos.md
> +For more details check out the [configuration]() section.
Needs to link the config section.

2021-10-08 15:20 UTC, jdknives commented on docs/software/skywire/setup/linux.md
> +        $ sudo snap install go --classic git make
Mh. I dont like Snap particularly. Would appreciate if we could link to manual installation instructions for Go on Debian.

2021-10-08 15:22 UTC, jdknives commented on docs/software/skywire/setup/docker.md
> +   <!-- # **Build**
Please keep your notes somewhere else or use TODOs or something like that.

2021-10-08 15:23 UTC, jdknives commented on docs/software/skywire/setup/docker.md
> +# **Run**
Make a similar note for installation here of Docker as we have for MacOS dependencies etc and just point out that the installation instructions are beyong the scope of this article.

2021-10-08 15:23 UTC, jdknives commented on docs/software/skywire/setup/docker.md
> +$ docker run --rm -p 8000:8000 --name=skywire skycoin/skywire:latest skywire-visor
Make a coloured note here (maybe blue as well) that using the latest tag will pull an image built from `master` branch and `test` will pull an image built from `develop` branch.

2021-10-08 15:25 UTC, jdknives commented on docs/software/skywire/setup/static-build.md
> +You can statically compile all Skywire binaries. Install musl-tools with a package manager of your choice.
Just point out that you can build static binaries on Linux and remove the mention of MacOS musl ports below. Add a blue section with install commands for musl on Debian and Arch.

2021-10-08 15:26 UTC, jdknives commented on docs/software/skywire/setup/static-build.md
> +# Installs all dependencies, build binaries and skywire apps
As with the other articles, please mvoe these comments out. We can add the build and install commands into one code block as we do for building and installing from source with `make build-static && make install-static`.

2021-10-08 15:27 UTC, jdknives commented on docs/software/skywire/setup/macos.md
> +$ make build; make install
Change this to `make build && make install` here and elsewhere please. No point in installing if the build target failed.

2021-10-08 15:34 UTC, libronlopes commented on docs/software/skywire/setup/static-build.md
> +You can statically compile all Skywire binaries. Install musl-tools with a package manager of your choice.
Okay

2021-10-08 15:35 UTC, libronlopes commented on docs/software/skywire/setup/macos.md
> +$ make build; make install
Okay

2021-10-13 11:01 UTC, jdknives commented on docs/software/skywire/configuration/hypervisor-mode.md
> +To generate config file manually for visor and expose hypervisorUI, run:
We need to preface what the hypervisor and the hypervisor UI in general terms. Why would I want to run it as a user? What can I do with it?

2021-10-13 11:01 UTC, jdknives commented on docs/software/skywire/configuration/hypervisor-mode.md
> +### **TLS**
What does that do? Why would I want to do that?

2021-10-13 11:01 UTC, jdknives commented on docs/software/skywire/configuration/hypervisor-mode.md
> +To change authentication settings in HypervisorUI, edit the hypervisor section in config file generated:
Where are these authentication settings used? When should such authentication be used?

2021-10-13 11:03 UTC, jdknives commented on docs/software/skywire/configuration/network-config.md
> +## Make visor public
Make a note here that the visor that is public will be relaying data for other visors and may be eligible for extra rewards.

2021-10-13 11:04 UTC, jdknives commented on docs/software/skywire/configuration/network-config.md
> +If public autoconnect is enabled it will search for public visors (those with `"is_public": true`) and connect them on startup via `stcpr`.
What is `it`? Is `public autoconnect` enabled by default?

2021-10-13 11:05 UTC, jdknives commented on docs/software/skywire/setup/docker.md
> +    To execute the commands below requires docker to be installed and setup. The instructions for same are beyond the scope of this article.
`The docker setup instructions are beyond the scope of this article. Please refer to Docker documentation for installing Docker on your system.`

2021-10-13 11:06 UTC, jdknives commented on docs/software/skywire/setup/static-build.md
> +You can build static binaries in Linux
Add some context. Why would someone want to build static binaries?

2021-10-14 12:28 UTC, jdknives commented on docs/software/skywire/setup/static-build.md
> +A statically build binary has all the required library code built in and, it runs on about any system of the same type it was compiled on. Static binaries eliminate the dependency on external librari
`built binary`. The comma after `and` can be removed. What do you mean by type specifically?

2021-10-14 12:28 UTC, jdknives commented on docs/software/skywire/setup/static-build.md
> +You can build static binaries in Linux
On Linux.

2021-10-14 12:30 UTC, jdknives commented on docs/software/skywire/configuration/hypervisor-mode.md
> +The hypervisorUI allows user to manage and monitor the skywire-visor nodes. These skywire-visor nodes run the Skywire protocol and also host the applications that user can use over the Skywire networ
`monitor Skywire visors`. `These visors run the Skywire protocol`. `applications that users can run on top of the Skywire network`.

2021-10-14 12:31 UTC, jdknives commented on docs/software/skywire/configuration/network-config.md
> +    A visor that is made public will be broadcasting data to other visors and may be eligible for extra rewards.
It does not technically `broadcast` the data. It relays/transmits/forwards it.

2021-10-15 11:11 UTC, merged