Docs/syslog
skycoin/wiki pull request #27
Opened 2021-12-03 16:28 UTC by libronlopes

add instructions for syslog setup, dmsghttp, autocomplete 
update golang version to 1.17 in instructions

2021-12-03 16:59 UTC, jdknives requested changes

2021-12-03 16:59 UTC, jdknives commented on docs/software/skywire/setup/syslog.md
> +In skywire uncomment `replace github.com/skycoin/dmsg => ../dmsg` in go.mod and run
Only necessary for now. Can be removed as the correct code will automatically be vendored once we push the PR.

2021-12-03 16:59 UTC, jdknives commented on docs/software/skywire/setup/syslog.md
> +$ ./skywire-visor -c skywire-config.json --syslog localhost:514
Note needs to be added that hostname needs to be used here if this does not work. Or check if we can use the output of `hostname` itself can be used

2021-12-06 09:32 UTC, libronlopes commented on docs/software/skywire/setup/syslog.md
> +In skywire uncomment `replace github.com/skycoin/dmsg => ../dmsg` in go.mod and run
Okay

2021-12-06 09:32 UTC, libronlopes commented on docs/software/skywire/setup/syslog.md
> +$ ./skywire-visor -c skywire-config.json --syslog localhost:514
okay

2021-12-10 18:15 UTC, merged